
package co.com.codesoftware.servicio.conteos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConteoWS", targetNamespace = "http://conteos.servicio.codesoftware.com.co/", wsdlLocation = "http://localhost:7777/SIGEMCOWS/ConteoWS?wsdl")
public class ConteoWS_Service
    extends Service
{

    private final static URL CONTEOWS_WSDL_LOCATION;
    private final static WebServiceException CONTEOWS_EXCEPTION;
    private final static QName CONTEOWS_QNAME = new QName("http://conteos.servicio.codesoftware.com.co/", "ConteoWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/SIGEMCOWS/ConteoWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTEOWS_WSDL_LOCATION = url;
        CONTEOWS_EXCEPTION = e;
    }

    public ConteoWS_Service() {
        super(__getWsdlLocation(), CONTEOWS_QNAME);
    }

    public ConteoWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTEOWS_QNAME, features);
    }

    public ConteoWS_Service(URL wsdlLocation) {
        super(wsdlLocation, CONTEOWS_QNAME);
    }

    public ConteoWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTEOWS_QNAME, features);
    }

    public ConteoWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConteoWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConteoWS
     */
    @WebEndpoint(name = "ConteoWSPort")
    public ConteoWS getConteoWSPort() {
        return super.getPort(new QName("http://conteos.servicio.codesoftware.com.co/", "ConteoWSPort"), ConteoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConteoWS
     */
    @WebEndpoint(name = "ConteoWSPort")
    public ConteoWS getConteoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://conteos.servicio.codesoftware.com.co/", "ConteoWSPort"), ConteoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTEOWS_EXCEPTION!= null) {
            throw CONTEOWS_EXCEPTION;
        }
        return CONTEOWS_WSDL_LOCATION;
    }

}
