
package co.com.codesoftware.servicio.conteos;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConteoWS", targetNamespace = "http://conteos.servicio.codesoftware.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConteoWS {


    /**
     * 
     * @param ubicacion
     * @param codExterno
     * @param codConteo
     * @param cantidad
     * @param codigoBarras
     * @return
     *     returns co.com.codesoftware.servicio.conteos.RespuestaEntity
     */
    @WebMethod
    @WebResult(name = "RespuestaEntity", targetNamespace = "")
    @RequestWrapper(localName = "insertaProductoConteo", targetNamespace = "http://conteos.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.conteos.InsertaProductoConteo")
    @ResponseWrapper(localName = "insertaProductoConteoResponse", targetNamespace = "http://conteos.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.conteos.InsertaProductoConteoResponse")
    @Action(input = "http://conteos.servicio.codesoftware.com.co/ConteoWS/insertaProductoConteoRequest", output = "http://conteos.servicio.codesoftware.com.co/ConteoWS/insertaProductoConteoResponse")
    public RespuestaEntity insertaProductoConteo(
        @WebParam(name = "codExterno", targetNamespace = "")
        String codExterno,
        @WebParam(name = "codConteo", targetNamespace = "")
        Integer codConteo,
        @WebParam(name = "cantidad", targetNamespace = "")
        Integer cantidad,
        @WebParam(name = "codigoBarras", targetNamespace = "")
        String codigoBarras,
        @WebParam(name = "ubicacion", targetNamespace = "")
        String ubicacion);

    /**
     * 
     * @param idConteo
     * @param codigoExterno
     * @return
     *     returns co.com.codesoftware.servicio.conteos.ProductoConteoEntity
     */
    @WebMethod
    @WebResult(name = "ProductoConteoEntityTR", targetNamespace = "")
    @RequestWrapper(localName = "obtenerProdConteo", targetNamespace = "http://conteos.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.conteos.ObtenerProdConteo")
    @ResponseWrapper(localName = "obtenerProdConteoResponse", targetNamespace = "http://conteos.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.conteos.ObtenerProdConteoResponse")
    @Action(input = "http://conteos.servicio.codesoftware.com.co/ConteoWS/obtenerProdConteoRequest", output = "http://conteos.servicio.codesoftware.com.co/ConteoWS/obtenerProdConteoResponse")
    public ProductoConteoEntity obtenerProdConteo(
        @WebParam(name = "codigoExterno", targetNamespace = "")
        String codigoExterno,
        @WebParam(name = "idConteo", targetNamespace = "")
        Integer idConteo);

    /**
     * 
     * @param idConteo
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.conteos.ProductoConteoEntity>
     */
    @WebMethod
    @WebResult(name = "ProductoConteoEntityTR", targetNamespace = "")
    @RequestWrapper(localName = "obtenerProductosConteo", targetNamespace = "http://conteos.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.conteos.ObtenerProductosConteo")
    @ResponseWrapper(localName = "obtenerProductosConteoResponse", targetNamespace = "http://conteos.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.conteos.ObtenerProductosConteoResponse")
    @Action(input = "http://conteos.servicio.codesoftware.com.co/ConteoWS/obtenerProductosConteoRequest", output = "http://conteos.servicio.codesoftware.com.co/ConteoWS/obtenerProductosConteoResponse")
    public List<ProductoConteoEntity> obtenerProductosConteo(
        @WebParam(name = "idConteo", targetNamespace = "")
        Integer idConteo);

    /**
     * 
     * @param estado
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.conteos.ConteoEntity>
     */
    @WebMethod
    @WebResult(name = "ConteosEntity", targetNamespace = "")
    @RequestWrapper(localName = "obtenerConteoEstado", targetNamespace = "http://conteos.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.conteos.ObtenerConteoEstado")
    @ResponseWrapper(localName = "obtenerConteoEstadoResponse", targetNamespace = "http://conteos.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.conteos.ObtenerConteoEstadoResponse")
    @Action(input = "http://conteos.servicio.codesoftware.com.co/ConteoWS/obtenerConteoEstadoRequest", output = "http://conteos.servicio.codesoftware.com.co/ConteoWS/obtenerConteoEstadoResponse")
    public List<ConteoEntity> obtenerConteoEstado(
        @WebParam(name = "estado", targetNamespace = "")
        String estado);

}
