
package co.com.codesoftware.servicio.general;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GeneralWS", targetNamespace = "http://general.servicio.codesoftware.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GeneralWS {


    /**
     * 
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.general.SedeEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerSedes", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.ObtenerSedes")
    @ResponseWrapper(localName = "obtenerSedesResponse", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.ObtenerSedesResponse")
    @Action(input = "http://general.servicio.codesoftware.com.co/GeneralWS/obtenerSedesRequest", output = "http://general.servicio.codesoftware.com.co/GeneralWS/obtenerSedesResponse")
    public List<SedeEntity> obtenerSedes();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generaReportes", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.GeneraReportes")
    @ResponseWrapper(localName = "generaReportesResponse", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.GeneraReportesResponse")
    @Action(input = "http://general.servicio.codesoftware.com.co/GeneralWS/generaReportesRequest", output = "http://general.servicio.codesoftware.com.co/GeneralWS/generaReportesResponse")
    public String generaReportes(
        @WebParam(name = "arg0", targetNamespace = "")
        List<MapaEntity> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<MapaEntity> arg1);

    /**
     * 
     * @param sede
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarSede", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.ActualizarSede")
    @ResponseWrapper(localName = "actualizarSedeResponse", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.ActualizarSedeResponse")
    @Action(input = "http://general.servicio.codesoftware.com.co/GeneralWS/actualizarSedeRequest", output = "http://general.servicio.codesoftware.com.co/GeneralWS/actualizarSedeResponse")
    public String actualizarSede(
        @WebParam(name = "sede", targetNamespace = "")
        SedeEntity sede);

    /**
     * 
     * @param idRemision
     * @param idRsfa
     * @param diasPlazo
     * @param idTius
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "respuesta", targetNamespace = "")
    @RequestWrapper(localName = "realizarFacturaXRemision", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.RealizarFacturaXRemision")
    @ResponseWrapper(localName = "realizarFacturaXRemisionResponse", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.RealizarFacturaXRemisionResponse")
    @Action(input = "http://general.servicio.codesoftware.com.co/GeneralWS/realizarFacturaXRemisionRequest", output = "http://general.servicio.codesoftware.com.co/GeneralWS/realizarFacturaXRemisionResponse")
    public String realizarFacturaXRemision(
        @WebParam(name = "idRemision", targetNamespace = "")
        int idRemision,
        @WebParam(name = "idTius", targetNamespace = "")
        int idTius,
        @WebParam(name = "idRsfa", targetNamespace = "")
        int idRsfa,
        @WebParam(name = "diasPlazo", targetNamespace = "")
        int diasPlazo);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.general.ResolucionFactEntity>
     */
    @WebMethod
    @WebResult(name = "resoluciones", targetNamespace = "")
    @RequestWrapper(localName = "obtenerResolucionesFact", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.ObtenerResolucionesFact")
    @ResponseWrapper(localName = "obtenerResolucionesFactResponse", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.ObtenerResolucionesFactResponse")
    @Action(input = "http://general.servicio.codesoftware.com.co/GeneralWS/obtenerResolucionesFactRequest", output = "http://general.servicio.codesoftware.com.co/GeneralWS/obtenerResolucionesFactResponse")
    public List<ResolucionFactEntity> obtenerResolucionesFact();

    /**
     * 
     * @param objEntity
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "respuesta", targetNamespace = "")
    @RequestWrapper(localName = "insertarResolucion", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.InsertarResolucion")
    @ResponseWrapper(localName = "insertarResolucionResponse", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.InsertarResolucionResponse")
    @Action(input = "http://general.servicio.codesoftware.com.co/GeneralWS/insertarResolucionRequest", output = "http://general.servicio.codesoftware.com.co/GeneralWS/insertarResolucionResponse")
    public String insertarResolucion(
        @WebParam(name = "objEntity", targetNamespace = "")
        ResolucionFactEntity objEntity);

    /**
     * 
     * @param idCliente
     * @param fechaIni
     * @param fechafin
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.general.RemisionEntity>
     */
    @WebMethod
    @WebResult(name = "remisiones", targetNamespace = "")
    @RequestWrapper(localName = "obtenerRemisionesXCliente", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.ObtenerRemisionesXCliente")
    @ResponseWrapper(localName = "obtenerRemisionesXClienteResponse", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.ObtenerRemisionesXClienteResponse")
    @Action(input = "http://general.servicio.codesoftware.com.co/GeneralWS/obtenerRemisionesXClienteRequest", output = "http://general.servicio.codesoftware.com.co/GeneralWS/obtenerRemisionesXClienteResponse")
    public List<RemisionEntity> obtenerRemisionesXCliente(
        @WebParam(name = "idCliente", targetNamespace = "")
        int idCliente,
        @WebParam(name = "fechaIni", targetNamespace = "")
        XMLGregorianCalendar fechaIni,
        @WebParam(name = "fechafin", targetNamespace = "")
        XMLGregorianCalendar fechafin);

    /**
     * 
     * @param idRemision
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.general.DetProdRemision>
     */
    @WebMethod
    @WebResult(name = "detalles", targetNamespace = "")
    @RequestWrapper(localName = "obtenerDetalleRemision", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.ObtenerDetalleRemision")
    @ResponseWrapper(localName = "obtenerDetalleRemisionResponse", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.ObtenerDetalleRemisionResponse")
    @Action(input = "http://general.servicio.codesoftware.com.co/GeneralWS/obtenerDetalleRemisionRequest", output = "http://general.servicio.codesoftware.com.co/GeneralWS/obtenerDetalleRemisionResponse")
    public List<DetProdRemision> obtenerDetalleRemision(
        @WebParam(name = "idRemision", targetNamespace = "")
        int idRemision);

    /**
     * 
     * @param objEntity
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "respuesta", targetNamespace = "")
    @RequestWrapper(localName = "actualizaResolucion", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.ActualizaResolucion")
    @ResponseWrapper(localName = "actualizaResolucionResponse", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.ActualizaResolucionResponse")
    @Action(input = "http://general.servicio.codesoftware.com.co/GeneralWS/actualizaResolucionRequest", output = "http://general.servicio.codesoftware.com.co/GeneralWS/actualizaResolucionResponse")
    public String actualizaResolucion(
        @WebParam(name = "objEntity", targetNamespace = "")
        ResolucionFactEntity objEntity);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.general.ParametrosEmpresaEntity>
     */
    @WebMethod
    @WebResult(name = "parametros", targetNamespace = "")
    @RequestWrapper(localName = "obtenerParametrosEmpresa", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.ObtenerParametrosEmpresa")
    @ResponseWrapper(localName = "obtenerParametrosEmpresaResponse", targetNamespace = "http://general.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.general.ObtenerParametrosEmpresaResponse")
    @Action(input = "http://general.servicio.codesoftware.com.co/GeneralWS/obtenerParametrosEmpresaRequest", output = "http://general.servicio.codesoftware.com.co/GeneralWS/obtenerParametrosEmpresaResponse")
    public List<ParametrosEmpresaEntity> obtenerParametrosEmpresa();

}
