
package co.com.codesoftware.servicio.general;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GeneralWS", targetNamespace = "http://general.servicio.codesoftware.com.co/", wsdlLocation = "http://localhost:7777/SIGEMCOWS/GeneralWS?wsdl")
public class GeneralWS_Service
    extends Service
{

    private final static URL GENERALWS_WSDL_LOCATION;
    private final static WebServiceException GENERALWS_EXCEPTION;
    private final static QName GENERALWS_QNAME = new QName("http://general.servicio.codesoftware.com.co/", "GeneralWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/SIGEMCOWS/GeneralWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GENERALWS_WSDL_LOCATION = url;
        GENERALWS_EXCEPTION = e;
    }

    public GeneralWS_Service() {
        super(__getWsdlLocation(), GENERALWS_QNAME);
    }

    public GeneralWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENERALWS_QNAME, features);
    }

    public GeneralWS_Service(URL wsdlLocation) {
        super(wsdlLocation, GENERALWS_QNAME);
    }

    public GeneralWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENERALWS_QNAME, features);
    }

    public GeneralWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeneralWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GeneralWS
     */
    @WebEndpoint(name = "GeneralWSPort")
    public GeneralWS getGeneralWSPort() {
        return super.getPort(new QName("http://general.servicio.codesoftware.com.co/", "GeneralWSPort"), GeneralWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeneralWS
     */
    @WebEndpoint(name = "GeneralWSPort")
    public GeneralWS getGeneralWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://general.servicio.codesoftware.com.co/", "GeneralWSPort"), GeneralWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GENERALWS_EXCEPTION!= null) {
            throw GENERALWS_EXCEPTION;
        }
        return GENERALWS_WSDL_LOCATION;
    }

}
