
package co.com.codesoftware.servicio.pedido;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PedidoWS", targetNamespace = "http://pedido.servicio.codesoftware.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PedidoWS {


    /**
     * 
     * @param idPedido
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.pedido.PedidoProductoEntity>
     */
    @WebMethod
    @WebResult(name = "productos", targetNamespace = "")
    @RequestWrapper(localName = "obtenerProductosPedido", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.ObtenerProductosPedido")
    @ResponseWrapper(localName = "obtenerProductosPedidoResponse", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.ObtenerProductosPedidoResponse")
    @Action(input = "http://pedido.servicio.codesoftware.com.co/PedidoWS/obtenerProductosPedidoRequest", output = "http://pedido.servicio.codesoftware.com.co/PedidoWS/obtenerProductosPedidoResponse")
    public List<PedidoProductoEntity> obtenerProductosPedido(
        @WebParam(name = "idPedido", targetNamespace = "")
        int idPedido);

    /**
     * 
     * @param pedido
     * @return
     *     returns co.com.codesoftware.servicio.pedido.RespuestaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertaPedidosProducto", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.InsertaPedidosProducto")
    @ResponseWrapper(localName = "insertaPedidosProductoResponse", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.InsertaPedidosProductoResponse")
    @Action(input = "http://pedido.servicio.codesoftware.com.co/PedidoWS/insertaPedidosProductoRequest", output = "http://pedido.servicio.codesoftware.com.co/PedidoWS/insertaPedidosProductoResponse")
    public RespuestaEntity insertaPedidosProducto(
        @WebParam(name = "pedido", targetNamespace = "")
        PedidoEntity pedido);

    /**
     * 
     * @param pedido
     * @param idPedido
     * @return
     *     returns co.com.codesoftware.servicio.pedido.RespuestaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertaProductosXPedido", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.InsertaProductosXPedido")
    @ResponseWrapper(localName = "insertaProductosXPedidoResponse", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.InsertaProductosXPedidoResponse")
    @Action(input = "http://pedido.servicio.codesoftware.com.co/PedidoWS/insertaProductosXPedidoRequest", output = "http://pedido.servicio.codesoftware.com.co/PedidoWS/insertaProductosXPedidoResponse")
    public RespuestaEntity insertaProductosXPedido(
        @WebParam(name = "pedido", targetNamespace = "")
        List<PedidoProductoEntity> pedido,
        @WebParam(name = "idPedido", targetNamespace = "")
        int idPedido);

    /**
     * 
     * @param pediPedi
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "imagen", targetNamespace = "")
    @RequestWrapper(localName = "generaCodigoPedido", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.GeneraCodigoPedido")
    @ResponseWrapper(localName = "generaCodigoPedidoResponse", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.GeneraCodigoPedidoResponse")
    @Action(input = "http://pedido.servicio.codesoftware.com.co/PedidoWS/generaCodigoPedidoRequest", output = "http://pedido.servicio.codesoftware.com.co/PedidoWS/generaCodigoPedidoResponse")
    public String generaCodigoPedido(
        @WebParam(name = "pedi_pedi", targetNamespace = "")
        int pediPedi);

    /**
     * 
     * @param pediEstado
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.pedido.PedidoEntity>
     */
    @WebMethod
    @WebResult(name = "PedidoEntity", targetNamespace = "")
    @RequestWrapper(localName = "consultaPedidosXEstado", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.ConsultaPedidosXEstado")
    @ResponseWrapper(localName = "consultaPedidosXEstadoResponse", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.ConsultaPedidosXEstadoResponse")
    @Action(input = "http://pedido.servicio.codesoftware.com.co/PedidoWS/consultaPedidosXEstadoRequest", output = "http://pedido.servicio.codesoftware.com.co/PedidoWS/consultaPedidosXEstadoResponse")
    public List<PedidoEntity> consultaPedidosXEstado(
        @WebParam(name = "pedi_estado", targetNamespace = "")
        String pediEstado);

    /**
     * 
     * @param fechaIni
     * @param idTius
     * @param fechaFin
     * @param pediEstado
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.pedido.PedidoEntity>
     */
    @WebMethod
    @WebResult(name = "PedidoEntity", targetNamespace = "")
    @RequestWrapper(localName = "consultaPedidosXFiltros", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.ConsultaPedidosXFiltros")
    @ResponseWrapper(localName = "consultaPedidosXFiltrosResponse", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.ConsultaPedidosXFiltrosResponse")
    @Action(input = "http://pedido.servicio.codesoftware.com.co/PedidoWS/consultaPedidosXFiltrosRequest", output = "http://pedido.servicio.codesoftware.com.co/PedidoWS/consultaPedidosXFiltrosResponse")
    public List<PedidoEntity> consultaPedidosXFiltros(
        @WebParam(name = "pedi_estado", targetNamespace = "")
        String pediEstado,
        @WebParam(name = "fechaIni", targetNamespace = "")
        XMLGregorianCalendar fechaIni,
        @WebParam(name = "fechaFin", targetNamespace = "")
        XMLGregorianCalendar fechaFin,
        @WebParam(name = "idTius", targetNamespace = "")
        int idTius);

    /**
     * 
     * @param estado
     * @param idPedido
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "respuesta", targetNamespace = "")
    @RequestWrapper(localName = "cambiaEstadoPedido", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.CambiaEstadoPedido")
    @ResponseWrapper(localName = "cambiaEstadoPedidoResponse", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.CambiaEstadoPedidoResponse")
    @Action(input = "http://pedido.servicio.codesoftware.com.co/PedidoWS/cambiaEstadoPedidoRequest", output = "http://pedido.servicio.codesoftware.com.co/PedidoWS/cambiaEstadoPedidoResponse")
    public boolean cambiaEstadoPedido(
        @WebParam(name = "idPedido", targetNamespace = "")
        int idPedido,
        @WebParam(name = "estado", targetNamespace = "")
        String estado);

    /**
     * 
     * @param idPedido
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "imagen", targetNamespace = "")
    @RequestWrapper(localName = "generaPdfCotizacion", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.GeneraPdfCotizacion")
    @ResponseWrapper(localName = "generaPdfCotizacionResponse", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.GeneraPdfCotizacionResponse")
    @Action(input = "http://pedido.servicio.codesoftware.com.co/PedidoWS/generaPdfCotizacionRequest", output = "http://pedido.servicio.codesoftware.com.co/PedidoWS/generaPdfCotizacionResponse")
    public String generaPdfCotizacion(
        @WebParam(name = "idPedido", targetNamespace = "")
        int idPedido);

    /**
     * 
     * @param idPedido
     * @return
     *     returns co.com.codesoftware.servicio.pedido.PedidoEntity
     */
    @WebMethod
    @WebResult(name = "pedido", targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatPrincPedidoXId", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.ObtenerDatPrincPedidoXId")
    @ResponseWrapper(localName = "obtenerDatPrincPedidoXIdResponse", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.ObtenerDatPrincPedidoXIdResponse")
    @Action(input = "http://pedido.servicio.codesoftware.com.co/PedidoWS/obtenerDatPrincPedidoXIdRequest", output = "http://pedido.servicio.codesoftware.com.co/PedidoWS/obtenerDatPrincPedidoXIdResponse")
    public PedidoEntity obtenerDatPrincPedidoXId(
        @WebParam(name = "idPedido", targetNamespace = "")
        int idPedido);

    /**
     * 
     * @param idCliente
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.pedido.PedidoEntity>
     */
    @WebMethod
    @WebResult(name = "listaPedidos", targetNamespace = "")
    @RequestWrapper(localName = "obtenerRemisionesPorCliente", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.ObtenerRemisionesPorCliente")
    @ResponseWrapper(localName = "obtenerRemisionesPorClienteResponse", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.ObtenerRemisionesPorClienteResponse")
    @Action(input = "http://pedido.servicio.codesoftware.com.co/PedidoWS/obtenerRemisionesPorClienteRequest", output = "http://pedido.servicio.codesoftware.com.co/PedidoWS/obtenerRemisionesPorClienteResponse")
    public List<PedidoEntity> obtenerRemisionesPorCliente(
        @WebParam(name = "idCliente", targetNamespace = "")
        int idCliente);

    /**
     * 
     * @param idCliente
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.pedido.PedidoEntity>
     */
    @WebMethod
    @WebResult(name = "listaPedidos", targetNamespace = "")
    @RequestWrapper(localName = "buscaCotizacionPorCliente", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.BuscaCotizacionPorCliente")
    @ResponseWrapper(localName = "buscaCotizacionPorClienteResponse", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.BuscaCotizacionPorClienteResponse")
    @Action(input = "http://pedido.servicio.codesoftware.com.co/PedidoWS/buscaCotizacionPorClienteRequest", output = "http://pedido.servicio.codesoftware.com.co/PedidoWS/buscaCotizacionPorClienteResponse")
    public List<PedidoEntity> buscaCotizacionPorCliente(
        @WebParam(name = "idCliente", targetNamespace = "")
        int idCliente);

    /**
     * 
     * @param arg1
     * @param idPedido
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "rta", targetNamespace = "")
    @RequestWrapper(localName = "generarRemision", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.GenerarRemision")
    @ResponseWrapper(localName = "generarRemisionResponse", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.GenerarRemisionResponse")
    @Action(input = "http://pedido.servicio.codesoftware.com.co/PedidoWS/generarRemisionRequest", output = "http://pedido.servicio.codesoftware.com.co/PedidoWS/generarRemisionResponse")
    public String generarRemision(
        @WebParam(name = "idPedido", targetNamespace = "")
        int idPedido,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param pediPedi
     * @return
     *     returns co.com.codesoftware.servicio.pedido.RespuestaPedidoEntity
     */
    @WebMethod
    @WebResult(name = "RespuestaPedidoEntity", targetNamespace = "")
    @RequestWrapper(localName = "obtenerPedidoXId", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.ObtenerPedidoXId")
    @ResponseWrapper(localName = "obtenerPedidoXIdResponse", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.ObtenerPedidoXIdResponse")
    @Action(input = "http://pedido.servicio.codesoftware.com.co/PedidoWS/obtenerPedidoXIdRequest", output = "http://pedido.servicio.codesoftware.com.co/PedidoWS/obtenerPedidoXIdResponse")
    public RespuestaPedidoEntity obtenerPedidoXId(
        @WebParam(name = "pedi_pedi", targetNamespace = "")
        int pediPedi);

    /**
     * 
     * @param pediEstado
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "eliminaPedido", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.EliminaPedido")
    @ResponseWrapper(localName = "eliminaPedidoResponse", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.pedido.EliminaPedidoResponse")
    @Action(input = "http://pedido.servicio.codesoftware.com.co/PedidoWS/eliminaPedidoRequest", output = "http://pedido.servicio.codesoftware.com.co/PedidoWS/eliminaPedidoResponse")
    public boolean eliminaPedido(
        @WebParam(name = "pedi_estado", targetNamespace = "")
        int pediEstado);

}
