
package co.com.codesoftware.servicio.pedido;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PedidoWS", targetNamespace = "http://pedido.servicio.codesoftware.com.co/", wsdlLocation = "http://localhost:8777/SIGEMCOWS/PedidoWS?wsdl")
public class PedidoWS_Service
    extends Service
{

    private final static URL PEDIDOWS_WSDL_LOCATION;
    private final static WebServiceException PEDIDOWS_EXCEPTION;
    private final static QName PEDIDOWS_QNAME = new QName("http://pedido.servicio.codesoftware.com.co/", "PedidoWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8777/SIGEMCOWS/PedidoWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PEDIDOWS_WSDL_LOCATION = url;
        PEDIDOWS_EXCEPTION = e;
    }

    public PedidoWS_Service() {
        super(__getWsdlLocation(), PEDIDOWS_QNAME);
    }

    public PedidoWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PEDIDOWS_QNAME, features);
    }

    public PedidoWS_Service(URL wsdlLocation) {
        super(wsdlLocation, PEDIDOWS_QNAME);
    }

    public PedidoWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PEDIDOWS_QNAME, features);
    }

    public PedidoWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PedidoWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PedidoWS
     */
    @WebEndpoint(name = "PedidoWSPort")
    public PedidoWS getPedidoWSPort() {
        return super.getPort(new QName("http://pedido.servicio.codesoftware.com.co/", "PedidoWSPort"), PedidoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PedidoWS
     */
    @WebEndpoint(name = "PedidoWSPort")
    public PedidoWS getPedidoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pedido.servicio.codesoftware.com.co/", "PedidoWSPort"), PedidoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PEDIDOWS_EXCEPTION!= null) {
            throw PEDIDOWS_EXCEPTION;
        }
        return PEDIDOWS_WSDL_LOCATION;
    }

}
