
package co.com.codesoftware.servicio.facturacion;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FacturacionWS", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FacturacionWS {


    /**
     * 
     * @param datosCancelacion
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelaFactura", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.CancelaFactura")
    @ResponseWrapper(localName = "cancelaFacturaResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.CancelaFacturaResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/cancelaFacturaRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/cancelaFacturaResponse")
    public String cancelaFactura(
        @WebParam(name = "DatosCancelacion", targetNamespace = "")
        CancelaFacturaWrapRequest datosCancelacion);

    /**
     * 
     * @param idFacturaCompra
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "llamaProcedimientoValoresFacturaTMP", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.LlamaProcedimientoValoresFacturaTMP")
    @ResponseWrapper(localName = "llamaProcedimientoValoresFacturaTMPResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.LlamaProcedimientoValoresFacturaTMPResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/llamaProcedimientoValoresFacturaTMPRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/llamaProcedimientoValoresFacturaTMPResponse")
    public String llamaProcedimientoValoresFacturaTMP(
        @WebParam(name = "idFacturaCompra", targetNamespace = "")
        Integer idFacturaCompra);

    /**
     * 
     * @param idCliente
     * @param fInicial
     * @param idFactura
     * @param codExterno
     * @param fFinal
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.facturacion.FacturaEntity>
     */
    @WebMethod
    @WebResult(name = "listaFacturas", targetNamespace = "")
    @RequestWrapper(localName = "obtenerFacturasConFiltros", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerFacturasConFiltros")
    @ResponseWrapper(localName = "obtenerFacturasConFiltrosResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerFacturasConFiltrosResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerFacturasConFiltrosRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerFacturasConFiltrosResponse")
    public List<FacturaEntity> obtenerFacturasConFiltros(
        @WebParam(name = "fInicial", targetNamespace = "")
        XMLGregorianCalendar fInicial,
        @WebParam(name = "fFinal", targetNamespace = "")
        XMLGregorianCalendar fFinal,
        @WebParam(name = "idFactura", targetNamespace = "")
        Integer idFactura,
        @WebParam(name = "idCliente", targetNamespace = "")
        Integer idCliente,
        @WebParam(name = "codExterno", targetNamespace = "")
        String codExterno);

    /**
     * 
     * @param idFactura
     * @return
     *     returns co.com.codesoftware.servicio.facturacion.FacturaEntity
     */
    @WebMethod
    @WebResult(name = "FacturaEntity", targetNamespace = "")
    @RequestWrapper(localName = "obtenerFacturaXId", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerFacturaXId")
    @ResponseWrapper(localName = "obtenerFacturaXIdResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerFacturaXIdResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerFacturaXIdRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerFacturaXIdResponse")
    public FacturaEntity obtenerFacturaXId(
        @WebParam(name = "idFactura", targetNamespace = "")
        int idFactura);

    /**
     * 
     * @param factFact
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "imagen", targetNamespace = "")
    @RequestWrapper(localName = "obtenerImagenXIdFactura", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerImagenXIdFactura")
    @ResponseWrapper(localName = "obtenerImagenXIdFacturaResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerImagenXIdFacturaResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerImagenXIdFacturaRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerImagenXIdFacturaResponse")
    public String obtenerImagenXIdFactura(
        @WebParam(name = "fact_fact", targetNamespace = "")
        String factFact);

    /**
     * 
     * @param estado
     * @param fInicial
     * @param fFinal
     * @param idSede
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.facturacion.FacturaEntity>
     */
    @WebMethod
    @WebResult(name = "listaFacturas", targetNamespace = "")
    @RequestWrapper(localName = "obtenerFacturasSede", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerFacturasSede")
    @ResponseWrapper(localName = "obtenerFacturasSedeResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerFacturasSedeResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerFacturasSedeRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerFacturasSedeResponse")
    public List<FacturaEntity> obtenerFacturasSede(
        @WebParam(name = "fInicial", targetNamespace = "")
        XMLGregorianCalendar fInicial,
        @WebParam(name = "fFinal", targetNamespace = "")
        XMLGregorianCalendar fFinal,
        @WebParam(name = "idSede", targetNamespace = "")
        int idSede,
        @WebParam(name = "estado", targetNamespace = "")
        String estado);

    /**
     * 
     * @param estado
     * @param idFactura
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.facturacion.MoviContableEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerMovimientoContableXFac", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerMovimientoContableXFac")
    @ResponseWrapper(localName = "obtenerMovimientoContableXFacResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerMovimientoContableXFacResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerMovimientoContableXFacRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerMovimientoContableXFacResponse")
    public List<MoviContableEntity> obtenerMovimientoContableXFac(
        @WebParam(name = "idFactura", targetNamespace = "")
        Integer idFactura,
        @WebParam(name = "estado", targetNamespace = "")
        String estado);

    /**
     * 
     * @param datosImagen
     * @param datosCancelacion
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertaImagenCancelacion", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.InsertaImagenCancelacion")
    @ResponseWrapper(localName = "insertaImagenCancelacionResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.InsertaImagenCancelacionResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/insertaImagenCancelacionRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/insertaImagenCancelacionResponse")
    public String insertaImagenCancelacion(
        @WebParam(name = "DatosCancelacion", targetNamespace = "")
        CancelaFacturaWrapRequest datosCancelacion,
        @WebParam(name = "DatosImagen", targetNamespace = "")
        ImagenFacturaEntity datosImagen);

    /**
     * 
     * @param idFactura
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.facturacion.ImagenFacturaEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consutaImagenFacturas", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ConsutaImagenFacturas")
    @ResponseWrapper(localName = "consutaImagenFacturasResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ConsutaImagenFacturasResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/consutaImagenFacturasRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/consutaImagenFacturasResponse")
    public List<ImagenFacturaEntity> consutaImagenFacturas(
        @WebParam(name = "idFactura", targetNamespace = "")
        Integer idFactura);

    /**
     * 
     * @param idFactura
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.facturacion.HistorialFacturaEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerHistorialFacXID", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerHistorialFacXID")
    @ResponseWrapper(localName = "obtenerHistorialFacXIDResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerHistorialFacXIDResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerHistorialFacXIDRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerHistorialFacXIDResponse")
    public List<HistorialFacturaEntity> obtenerHistorialFacXID(
        @WebParam(name = "IdFactura", targetNamespace = "")
        Integer idFactura);

    /**
     * 
     * @param facturaCompraTmp
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarFacturaCompraTmp", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.InsertarFacturaCompraTmp")
    @ResponseWrapper(localName = "insertarFacturaCompraTmpResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.InsertarFacturaCompraTmpResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/insertarFacturaCompraTmpRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/insertarFacturaCompraTmpResponse")
    public Integer insertarFacturaCompraTmp(
        @WebParam(name = "facturaCompraTmp", targetNamespace = "")
        FacturaCompraTmpEntity facturaCompraTmp);

    /**
     * 
     * @param facturaCompraTmp
     * @return
     *     returns co.com.codesoftware.servicio.facturacion.FacturaCompraTmpEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarFacturaCompraTmp", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ActualizarFacturaCompraTmp")
    @ResponseWrapper(localName = "actualizarFacturaCompraTmpResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ActualizarFacturaCompraTmpResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/actualizarFacturaCompraTmpRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/actualizarFacturaCompraTmpResponse")
    public FacturaCompraTmpEntity actualizarFacturaCompraTmp(
        @WebParam(name = "facturaCompraTmp", targetNamespace = "")
        FacturaCompraTmpEntity facturaCompraTmp);

    /**
     * 
     * @param estado
     * @param fInicial
     * @param fFinal
     * @param idSede
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.facturacion.FacturaCompraTmpEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerFacturasCompraTmp", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerFacturasCompraTmp")
    @ResponseWrapper(localName = "obtenerFacturasCompraTmpResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerFacturasCompraTmpResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerFacturasCompraTmpRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerFacturasCompraTmpResponse")
    public List<FacturaCompraTmpEntity> obtenerFacturasCompraTmp(
        @WebParam(name = "estado", targetNamespace = "")
        String estado,
        @WebParam(name = "fInicial", targetNamespace = "")
        XMLGregorianCalendar fInicial,
        @WebParam(name = "fFinal", targetNamespace = "")
        XMLGregorianCalendar fFinal,
        @WebParam(name = "idSede", targetNamespace = "")
        Integer idSede);

    /**
     * 
     * @param idFactCompraTmp
     * @param listaProductos
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.facturacion.ProdFacCompraTmpEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarProdFacturasCompraTmp", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.InsertarProdFacturasCompraTmp")
    @ResponseWrapper(localName = "insertarProdFacturasCompraTmpResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.InsertarProdFacturasCompraTmpResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/insertarProdFacturasCompraTmpRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/insertarProdFacturasCompraTmpResponse")
    public List<ProdFacCompraTmpEntity> insertarProdFacturasCompraTmp(
        @WebParam(name = "listaProductos", targetNamespace = "")
        List<ProdFacCompraTmpEntity> listaProductos,
        @WebParam(name = "idFactCompraTmp", targetNamespace = "")
        Integer idFactCompraTmp);

    /**
     * 
     * @param idFactCompraTmp
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.facturacion.ProdFacCompraTmpEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerProdFacturasCompraTmp", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerProdFacturasCompraTmp")
    @ResponseWrapper(localName = "obtenerProdFacturasCompraTmpResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerProdFacturasCompraTmpResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerProdFacturasCompraTmpRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerProdFacturasCompraTmpResponse")
    public List<ProdFacCompraTmpEntity> obtenerProdFacturasCompraTmp(
        @WebParam(name = "idFactCompraTmp", targetNamespace = "")
        Integer idFactCompraTmp);

    /**
     * 
     * @param idFacturaCompra
     * @return
     *     returns co.com.codesoftware.servicio.facturacion.FacturaCompraTmpEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerFactTempCompraXId", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerFactTempCompraXId")
    @ResponseWrapper(localName = "obtenerFactTempCompraXIdResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerFactTempCompraXIdResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerFactTempCompraXIdRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerFactTempCompraXIdResponse")
    public FacturaCompraTmpEntity obtenerFactTempCompraXId(
        @WebParam(name = "idFacturaCompra", targetNamespace = "")
        Integer idFacturaCompra);

    /**
     * 
     * @param idFacturaCompra
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "llamaProcedimientoFacturaTMP", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.LlamaProcedimientoFacturaTMP")
    @ResponseWrapper(localName = "llamaProcedimientoFacturaTMPResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.LlamaProcedimientoFacturaTMPResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/llamaProcedimientoFacturaTMPRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/llamaProcedimientoFacturaTMPResponse")
    public String llamaProcedimientoFacturaTMP(
        @WebParam(name = "idFacturaCompra", targetNamespace = "")
        Integer idFacturaCompra);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.codesoftware.servicio.facturacion.FacturaCompraEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaFacturasVencidas", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ConsultaFacturasVencidas")
    @ResponseWrapper(localName = "consultaFacturasVencidasResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ConsultaFacturasVencidasResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/consultaFacturasVencidasRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/consultaFacturasVencidasResponse")
    public List<FacturaCompraEntity> consultaFacturasVencidas();

    /**
     * 
     * @param facturacion
     * @return
     *     returns co.com.codesoftware.servicio.facturacion.RespuestaFacturacion
     */
    @WebMethod
    @WebResult(name = "respuestaFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "facturarAvanzada", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.FacturarAvanzada")
    @ResponseWrapper(localName = "facturarAvanzadaResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.FacturarAvanzadaResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/facturarAvanzadaRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/facturarAvanzadaResponse")
    public RespuestaFacturacion facturarAvanzada(
        @WebParam(name = "Facturacion", targetNamespace = "")
        FacturacionGenEntity facturacion);

    /**
     * 
     * @param facturacion
     * @return
     *     returns co.com.codesoftware.servicio.facturacion.RespuestaFacturacion
     */
    @WebMethod
    @WebResult(name = "respuestaFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "facturar", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.Facturar")
    @ResponseWrapper(localName = "facturarResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.FacturarResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/facturarRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/facturarResponse")
    public RespuestaFacturacion facturar(
        @WebParam(name = "facturacion", targetNamespace = "")
        FacturacionGenEntity facturacion);

    /**
     * 
     * @param sede
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(name = "cantidad", targetNamespace = "")
    @RequestWrapper(localName = "obtenerValorCaja", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerValorCaja")
    @ResponseWrapper(localName = "obtenerValorCajaResponse", targetNamespace = "http://facturacion.servicio.codesoftware.com.co/", className = "co.com.codesoftware.servicio.facturacion.ObtenerValorCajaResponse")
    @Action(input = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerValorCajaRequest", output = "http://facturacion.servicio.codesoftware.com.co/FacturacionWS/obtenerValorCajaResponse")
    public BigDecimal obtenerValorCaja(
        @WebParam(name = "sede", targetNamespace = "")
        int sede);

}
